# https://github.com/bhautik0012/Government-potal
services:
  - type: web
    name: government-potal
    runtime: python
    plan: free
    rootDir: Government
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CI
        value: "false"
